config/routes.rb
Rails.application.routes.draw do
  resources :tipos
  resources :equipos
  resources :temperaturas
  resources :fases
  resources :materiales
  resources :quemas
  devise_for :users
  root 'home#index'
  get 'home/about'

end

app/models/temperatura.rb
class Temperatura < ActiveRecord::Base
end

app/controllers/temperaturas_controller.rb
class TemperaturasController < ApplicationController
  before_action :set_temperatura, only: [:show, :edit, :update, :destroy]

  # GET /temperaturas
  # GET /temperaturas.json
  def index
    @temperaturas = Temperatura.all
  end

  # GET /temperaturas/1
  # GET /temperaturas/1.json
  def show
  end

  # GET /temperaturas/new
  def new
    @temperatura = Temperatura.new
  end

  # GET /temperaturas/1/edit
  def edit
  end

  # POST /temperaturas
  # POST /temperaturas.json
  def create
    @temperatura = Temperatura.new(temperatura_params)

    respond_to do |format|
      if @temperatura.save
        format.html { redirect_to @temperatura, notice: 'Temperatura was successfully created.' }
        format.json { render :show, status: :created, location: @temperatura }
      else
        format.html { render :new }
        format.json { render json: @temperatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temperaturas/1
  # PATCH/PUT /temperaturas/1.json
  def update
    respond_to do |format|
      if @temperatura.update(temperatura_params)
        format.html { redirect_to @temperatura, notice: 'Temperatura was successfully updated.' }
        format.json { render :show, status: :ok, location: @temperatura }
      else
        format.html { render :edit }
        format.json { render json: @temperatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temperaturas/1
  # DELETE /temperaturas/1.json
  def destroy
    @temperatura.destroy
    respond_to do |format|
      format.html { redirect_to temperaturas_url, notice: 'Temperatura was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temperatura
      @temperatura = Temperatura.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def temperatura_params
      params.require(:temperatura).permit(:valor)
    end
end

app/helpers/temperaturas_helper.rb
module TemperaturasHelper
end

app/views/temperaturas/_form.html.erb
<%= form_for(@temperatura) do |f| %>
  <% if @temperatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@temperatura.errors.count, "error") %> prohibited this temperatura from being saved:</h2>

      <ul>
      <% @temperatura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :valor %><br>
    <%= f.number_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/temperaturas/edit.html.erb
<h1>Editing Temperatura</h1>

<%= render 'form' %>

<%= link_to 'Show', @temperatura %> |
<%= link_to 'Back', temperaturas_path %>

app/views/temperaturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Temperaturas</h1>

<table>
  <thead>
    <tr>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @temperaturas.each do |temperatura| %>
      <tr>
        <td><%= temperatura.valor %></td>
        <td><%= link_to 'Show', temperatura %></td>
        <td><%= link_to 'Edit', edit_temperatura_path(temperatura) %></td>
        <td><%= link_to 'Destroy', temperatura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Temperatura', new_temperatura_path %>

app/views/temperaturas/new.html.erb
<h1>New Temperatura</h1>

<%= render 'form' %>

<%= link_to 'Back', temperaturas_path %>

app/views/temperaturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valor:</strong>
  <%= @temperatura.valor %>
</p>

<%= link_to 'Edit', edit_temperatura_path(@temperatura) %> |
<%= link_to 'Back', temperaturas_path %>