config/routes.rb
Rails.application.routes.draw do
  resources :tipos
  resources :equipos
  resources :temperaturas
  resources :fases
  resources :materiales
  resources :quemas
  devise_for :users
  root 'home#index'
  get 'home/about'

end

app/models/materiale.rb
class Materiale < ActiveRecord::Base
    has_many :quemas
end

app/controllers/materiales_controller.rb
class MaterialesController < ApplicationController
  before_action :set_materiale, only: [:show, :edit, :update, :destroy]

  # GET /materiales
  # GET /materiales.json
  def index
    @materiales = Materiale.all
  end

  # GET /materiales/1
  # GET /materiales/1.json
  def show
  end

  # GET /materiales/new
  def new
    @materiale = Materiale.new
  end

  # GET /materiales/1/edit
  def edit
  end

  # POST /materiales
  # POST /materiales.json
  def create
    @materiale = Materiale.new(materiale_params)

    respond_to do |format|
      if @materiale.save
        format.html { redirect_to @materiale, notice: 'Materiale was successfully created.' }
        format.json { render :show, status: :created, location: @materiale }
      else
        format.html { render :new }
        format.json { render json: @materiale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materiales/1
  # PATCH/PUT /materiales/1.json
  def update
    respond_to do |format|
      if @materiale.update(materiale_params)
        format.html { redirect_to @materiale, notice: 'Materiale was successfully updated.' }
        format.json { render :show, status: :ok, location: @materiale }
      else
        format.html { render :edit }
        format.json { render json: @materiale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materiales/1
  # DELETE /materiales/1.json
  def destroy
    @materiale.destroy
    respond_to do |format|
      format.html { redirect_to materiales_url, notice: 'Materiale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_materiale
      @materiale = Materiale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def materiale_params
      params.require(:materiale).permit(:nombre)
    end
end

app/helpers/materiales_helper.rb
module MaterialesHelper
end

app/views/materiales/_form.html.erb
<%= form_for(@materiale) do |f| %>
  <% if @materiale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@materiale.errors.count, "error") %> prohibited this materiale from being saved:</h2>

      <ul>
      <% @materiale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materiales/edit.html.erb
<h1>Editing Materiale</h1>

<%= render 'form' %>

<%= link_to 'Ver', @materiale %> |
<%= link_to 'Regresar', materiales_path %>

app/views/materiales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Materiales</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materiales.each do |materiale| %>
      <tr>
        <td><%= materiale.nombre %></td>
        <td><%= link_to 'Ver', materiale %></td>
        <td><%= link_to 'Editar', edit_materiale_path(materiale) %></td>
        <td><%= link_to 'Destroy', materiale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Material', new_materiale_path %>

app/views/materiales/new.html.erb
<h1>New Materiale</h1>

<%= render 'form' %>

<%= link_to 'Atras', materiales_path %>

app/views/materiales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @materiale.nombre %>
</p>

<%= link_to 'Editar', edit_materiale_path(@materiale) %> |
<%= link_to 'Atras', materiales_path %>