config/routes.rb
Rails.application.routes.draw do
  resources :tipos
  resources :equipos
  resources :temperaturas
  resources :fases
  resources :materiales
  resources :quemas
  devise_for :users
  root 'home#index'
  get 'home/about'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<div class="top-bar-dark">            
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-right">
                <ul class="list-inline top-dark-right">
                <% if user_signed_in? %>
                  <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to 'Iniciar Sesión', new_user_session_path %></li>
                  <li><%= link_to 'Registro', new_user_registration_path %></li>
                <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>

<nav class="navbar navbar-default">
    
  <div class="container">
    
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <!-- Nombre de la empresa, link a homepage> -->
      <%= link_to 'Decovi', root_path, class:"navbar-brand" %>
    
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        
        <ul class="nav navbar-nav navbar-right" >
            <li class="drowpdown"><%= link_to 'Inicio', root_path %></li>
            <li class="drowpdown"><%= link_to 'El Proyecto', home_about_path %></li>
          
            <% if user_signed_in? %>
              
              <li class="drowpdown"><%= link_to 'Horno', quemas_path %></li>
              <li class="dropdown">
              
                <!-- Dorpdown nombre: adminsitrar-->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administrar</a>
                <!-- Dorpdown contenido: Editar-->
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Materiales', materiales_path %></li>
                  <li><%= link_to 'Fases', fases_path %></li>
                  <li><%= link_to 'Equipos', equipos_path %></li>
                  <li><%= link_to 'Tipos', tipos_path %></li>
                  
                </ul>
              
              </li>
              
            <% end %>
        </ul>
    
    </div><!-- /.navbar-collapse -->
  
  </div><!-- /.container -->

</nav>

app/views/home/about.html.erb
<h1>Nosotros</h1>
<p>
    Codigo de ejemplo sobre la información de la aplicación web
</p>

                <section id="main-content">

                    <div class="space-30"></div>

                    <!--Chart container start-->
                    <div class="container">

                        <div class="row">

                            <div class="col-md-12">
                                <div class="panel">
                                    
                                    <header class="panel-heading">
                                        <div class="panel-actions">
                                            <a href="#" class="panel-action panel-action-toggle" data-panel-toggle=""></a>
                                            <a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss=""></a>
                                        </div>
                                        <h2 class="panel-title">Morris One line chart </h2>
                                    </header>

                                    <div class="panel-body">
                                        <div class="morris-chart-data">
                                            <morris></morris>
                                        </div>
                                    </div>

                                </div>
                            </div>  <!--col end--> 

                        </div>

                    </div>
                    <!--Chart container end-->

                    <!--footer start-->
                    <div class="footer">
                        <div class="row">
                            <div class="col-sm-12">
                                <span>&copy; Copyright 2016. Assan</span>
                            </div>
                        </div>
                    </div>
                    <!--footer end-->

                </section><!--end main content-->
                
                

app/views/home/index.html.erb
<div class="jumbotron">
  
  <h2>Control del Horno</h2>
  
  <p> 
    Esta sección permite el control del horno de vitrificado. 
    Se puede iniciar un ciclo de quema para productos de vidrio,
    para produtos de cerámica.
  </p>
  
  <div class="row">
      <div class="col-md-12">
          <div class="panel">
            
              <header class="panel-heading">
                  <div class="panel-actions">
                    
                      <%= link_to '',  class: 'panel-action panel-action-toggle' %>
                  </div>
                  <h2 class="panel-title"> Temperatura actual </h2>

              </header>
              
              <div class="panel-body">
                  <div class="morris-chart-data">
                    <%= content_tag(:div, class: 'morris-chart-dat') %>
                        <morris><%= content_tag(:div, class: 'morris-chart-dat') %></morris>
                    
                      </div>
                  </div>
              </div>
              
          </div>
      </div>  <!--col end--> 
      
  <div>
    <%= link_to 'Vidrio', home_about_path, class: 'btn btn-success' %>
    <%= link_to 'Cerámica', home_about_path, class: 'btn btn-success' %>
    <%= link_to 'Paro de emergencia', home_about_path, class: 'btn btn-danger' %>
  </div>
      
      <div>
    
        <h3>Funciones</h3>
      
        <p>
          <b>Vidrio:</b> Inicia ciclo de quema para vidrio.           Temp de fusión: 610 ºC   Tiempo de maduración: 80 min <br/>
          <b>Cerámica:</b> Inicia ciclo de quema con para cerámica.   Temp de fusión: 750 ºC   Tiempo de maduración: 5 min <br/>
          <b>Paro de emergencia:</b> Interrumpe el ciclo de quema, cierra todas las valvulas de gás incluido el suministro principal, apaga los quemadores y ventiladores.  
        </p>
      
      </div>
  </div>
</div>


    