config/routes.rb
Rails.application.routes.draw do
  resources :tipos
  resources :equipos
  resources :temperaturas
  resources :fases
  resources :materiales
  resources :quemas
  devise_for :users
  root 'home#index'
  get 'home/about'

end

app/models/quema.rb
class Quema < ActiveRecord::Base
end

app/controllers/quemas_controller.rb
class QuemasController < ApplicationController
  before_action :set_quema, only: [:show, :edit, :update, :destroy]

  # GET /quemas
  # GET /quemas.json
  def index
    @quemas = Quema.all
  end

  # GET /quemas/1
  # GET /quemas/1.json
  def show
  end

  # GET /quemas/new
  def new
    @quema = Quema.new
  end

  # GET /quemas/1/edit
  def edit
  end

  # POST /quemas
  # POST /quemas.json
  def create
    @quema = Quema.new(quema_params)

    respond_to do |format|
      if @quema.save
        format.html { redirect_to @quema, notice: 'Quema was successfully created.' }
        format.json { render :show, status: :created, location: @quema }
      else
        format.html { render :new }
        format.json { render json: @quema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quemas/1
  # PATCH/PUT /quemas/1.json
  def update
    respond_to do |format|
      if @quema.update(quema_params)
        format.html { redirect_to @quema, notice: 'Quema was successfully updated.' }
        format.json { render :show, status: :ok, location: @quema }
      else
        format.html { render :edit }
        format.json { render json: @quema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quemas/1
  # DELETE /quemas/1.json
  def destroy
    @quema.destroy
    respond_to do |format|
      format.html { redirect_to quemas_url, notice: 'Quema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quema
      @quema = Quema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quema_params
      params.require(:quema).permit(:estado)
    end
end

app/helpers/quemas_helper.rb
module QuemasHelper
end

app/views/quemas/_form.html.erb
<%= form_for(@quema) do |f| %>
  <% if @quema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quema.errors.count, "error") %> prohibited this quema from being saved:</h2>

      <ul>
      <% @quema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :estado %><br>
    <%= f.check_box :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quemas/edit.html.erb
<h1>Editing Quema</h1>

<%= render 'form' %>

<%= link_to 'Ver', @quema %> |
<%= link_to 'Atras', quemas_path %>

app/views/quemas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Historial de quemas</h1>

<table>
  <thead>
    <tr>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quemas.each do |quema| %>
      <tr>
        <td><%= quema.estado %></td>
        <td><%= link_to 'Ver', quema %></td>
        <td><%= link_to 'Editar', edit_quema_path(quema) %></td>
        <td><%= link_to 'Destroy', quema, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Quema', new_quema_path %>

app/views/quemas/new.html.erb
<h1>New Quema</h1>

<%= render 'form' %>

<%= link_to 'Atras', quemas_path %>

app/views/quemas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estado:</strong>
  <%= @quema.estado %>
</p>

<%= link_to 'Editar', edit_quema_path(@quema) %> |
<%= link_to 'Atras', quemas_path %>